version: "3"
services:
    postgres:
        container_name: some-postgres
        build: 
            context: .
            dockerfile: Dockerfile-postgres
        ports:
            - "5432:5432"
        networks:
            - iroha-network
    iroha:
        container_name: iroha
#        build:
#           context: .
#           dockerfile: Dockerfile-iroha
        image: gamma749/iroha-example
        ports:
            - "50051:50051"
        networks:
            - iroha-network
        volumes:
            - ./iroha/example:/opt/iroha_data
            - blockstore:/tmp/block_store
            - ./test-scripts:/opt/test-scripts

volumes:
    blockstore:

networks:
    iroha-network:
